version: '3'
services:
  web:
    image: nginx:latest
    container_name: webserver
    ports: 
      - "8090:80"
    volumes:
      - ../:/var/www/html/
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - code-network
  app:
    image: php:7-fpm
    container_name: app
    volumes:
      - ../app:/var/www/html/app/
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - code-network
  cart:
    image: php:7-fpm
    container_name: cart
    volumes:
      - ../ms_cart:/var/www/html/ms_cart/
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - code-network
  category:
    image: php:7-fpm
    container_name: category
    volumes:
      - ../ms_cart:/var/www/html/ms_category/
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - code-network
  pages:
    image: php:7-fpm
    container_name: pages
    volumes:
      - ../ms_cart:/var/www/html/ms_pages/
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - code-network
networks:
  code-network:
    driver: bridge