version: '3'
services:
  web:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports: 
      - "8090:80"
    volumes:
      - ../:/var/www/html/
      - ./conf.d:/etc/nginx/conf.d
    networks:
      code-network:
        aliases:
          - app.public.esigns
          - user.public.esigns
          - cart.public.esigns
          - category.public.esigns
          - pages.public.esigns
          - templates.public.esigns
          - products.public.esigns
          - artboard.public.esigns
          # - art.public.esigns
    depends_on:
      - app
      - cart
      - pages
      - category
      - templates
      - products
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - sqldata:/var/lib/mysql
    networks: 
      esigns-network:
        aliases:
          - mysql.docker.local
  app:
    image: mikechernev/php7-fpm-laravel
    container_name: app
    restart: unless-stopped
    volumes:
      - ../app:/var/www/html/app/
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      - composerdata:/root/.composer/
    networks:
      code-network:
        aliases: 
          - app.public.esigns
    depends_on:
      - user
      - category
      - cart
      - pages
      - templates
      - products
  cart:
    image: mikechernev/php7-fpm-laravel
    container_name: cart
    restart: unless-stopped
    volumes:
      - ../ms_cart:/var/www/html/ms_cart/
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      - composerdata:/root/.composer/
    networks:
      code-network:
        aliases:
          - cart.public.esigns
  category:
    image: mikechernev/php7-fpm-laravel
    container_name: category
    restart: unless-stopped
    volumes:
      - ../ms_category:/var/www/html/ms_category/
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      - composerdata:/root/.composer/
    networks:
      code-network:
        aliases:
          - category.public.esigns
  pages:
    image: mikechernev/php7-fpm-laravel
    container_name: pages
    restart: unless-stopped
    volumes:
      - ../ms_pages:/var/www/html/ms_pages/
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      - composerdata:/root/.composer/
    networks:
      code-network:
        aliases:
          - pages.public.esigns
  user:
    image: mikechernev/php7-fpm-laravel
    container_name: user
    restart: unless-stopped
    volumes:
      - ../ms_user:/var/www/html/ms_user/
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      - composerdata:/root/.composer/
    networks: 
      code-network:
        aliases:
          - user.public.esigns
    depends_on:
      - cart
  templates:
    image: mikechernev/php7-fpm-laravel
    container_name: templates
    restart: unless-stopped
    volumes:
      - ../ms_templates:/var/www/html/ms_templates/
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      - composerdata:/root/.composer/
    networks: 
      code-network:
        aliases:
          - templates.public.esigns
  products:
    image: mikechernev/php7-fpm-laravel
    container_name: products
    restart: unless-stopped
    volumes:
      - ../ms_products:/var/www/html/ms_products/
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      - composerdata:/root/.composer/
    networks: 
      code-network:
        aliases:
          - templates.public.esigns
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      code-network:
        aliases:
          - redis.public.esigns
  artboard:
    image: node:latest
    container_name: artboard
    restart: unless-stopped
    working_dir: /var/www/html/artboard
    volumes:
      - ../artboard:/var/www/html/artboard/
    ports:
      - "8060:8060"
    command: npm start
    networks: 
      code-network:
        aliases:
          - artboard.public.esigns

networks:
  code-network:
    driver: bridge

volumes:
  sqldata:
  composerdata: